// (C) 2001-2015 Altera Corporation. All rights reserved.
// This simulation model contains highly confidential and
// proprietary information of Altera and is being provided
// in accordance with and subject to the protections of the
// applicable Altera Program License Subscription Agreement
// which governs its use and disclosure. Your use of Altera
// Corporation's design tools, logic functions and other
// software and tools, and its AMPP partner logic functions,
// and any output files any of the foregoing (including device
// programming or simulation files), and any associated
// documentation or information are expressly subject to the
// terms and conditions of the Altera Program License Subscription
// Agreement, Altera MegaCore Function License Agreement, or other
// applicable license agreement, including, without limitation,
// that your use is for the sole purpose of simulating designs
// for use exclusively in logic devices manufactured by Altera and sold
// by Altera or its authorized distributors. Please refer to the
// applicable agreement for further details. Altera products and
// services are protected under numerous U.S. and foreign patents,
// maskwork rights, copyrights and other intellectual property laws.
// Altera assumes no responsibility or liability arising out of the
// application or use of this simulation model.
// ACDS 15.1
//pragma protect begin_protected
//pragma protect key_keyowner=Cadence Design Systems.
//pragma protect key_keyname=CDS_KEY
//pragma protect key_method=RC5
//pragma protect key_block
CjYiAlchTAoF1AMC+542Ky+XNJwOfjSGVFvG0ESP6XsG5VwvWZOB9O00OTAlttYQ
if1a4uwUhm8aaxnHp+T+uYDKQ8+50bj96RTMGiM0LiojhEXZmuGxj+B1dVudMLi7
nfpCcWSdMfXKT+m3uHt2ALGAjPfY5HeGBTlTHDGZka/jQiqdoFjniw==
//pragma protect end_key_block
//pragma protect digest_block
mXmJlWVN0c8dCcV9vXyI082Ff3g=
//pragma protect end_digest_block
//pragma protect data_block
7tOX1cM9NbhYHJ8i+/xweKcJmaNykpDb4uBbdqLQTwtonzz8cqiPTSQMQMGhwaz7
n/2W8kD7edNjhMTR/QqUNt35GDcw0Qt90PTixKkfw+hcopXPaV0P884yQlnrdpJU
Zk0jPlxVEq/pf98iLPR8bfZjEgpHWqiDHdAf7ltdRzgEUvgZf/j1MkGDuvgzFpaz
qcH9/BUOFL8GiO1F6/nyYu4i/LFUn20JDISGivRY8d+2idhnLUqakAymAYg+VLoT
BzGIhjp8Sgo5+yJMtLE4jPaLhZaXfLtdMB82vbAxLhZZL7M5inqSzC+EvDiU/4fI
k2MbhXG1f/JwYQZqYtiS31bmwJQNWnxfhackSInbXG8/pkU3wiZBVgUg/1/Z+kMC
WCCPkS3MRrDZEI3r+dgc+8pdVPj0w6ChRteZ+gFgYeXNfTfgsybQlPYk/FDeB9Qa
4vTsrHGJxkRRb/2Qfzl2x5K4+NzGmyLpGHJ/bO1XieYvpyXGalC2rWrj85ZvtdzG
oNf3zHnGjLvtGb0mY9w8LMHhn+oUCzKYN627cCEElnuiwHPEQse0UWaBB31Nkpjv
QVLYFu5+r6vZNO/FkRCgL5/+6TqmmTse/rkvTUWFKWwOF7N2875mIDJNwTrszBfR
zKOqxXRntLUeHcYXoPHAxyqxpB4gsBpfDT9NXDtCX3rlpm+cwoAO5efo56WlwdNN
Ek7lj4II+0SKXPsYdVY06WPbEtq15tS2T2uZYws4GR2Ww2X7t3rXqiMooS3iCy5N
iLXi6V+roXeQB/reTpgTFGERq4B7MLvS4BhFEcAa5rPg0zAEzxvTzT1vRgXUnQIS
VoukU64yTKK9gVIXM8mt6bMUrIIxvZF5Y4/ABFRZztGNSz1DXZDaQrtBj5Fgnf/8
UCTpINER5lWwhGmQFJ7gyHgWv6vbO5j4ut6/QOVZCwx3Tsdc0VxdTp8qwEh07Pci
MRb3eVs/tKBs5FDDdaO4wAX6InidRZeRaQtTLVm2MCnxPC2HQ/VsoAizDPrd5631
vRawXC28+Z6HFS169RRNFUxfe0fdGu9nYE34XgHpOGu10vv1xKp+7uNh0ssWZ6a0
qibX6M2FPkYCuzOu0ZESP39t9ERxT1bdN/ydSla4UsdukftYYokyhnbXwQIVW0j0
LH5fxE4XSsAzbERKvYNhaGaZ6ilUB9fXFM//1hg4N+S6IMP6CXvfXuukGtRftKUL
vOprez2IChQwVGQNNfJwkRSlaIBF3TUOTznxcZCGL2kmb147zdAMBuXYaJsM/tVF
0iO0R0awwQNbNt9gzXqDFgG4lkPA6PgHWDZt7MWtS/dqmoLHT30ppmmIMNC6k+WB
bnlDD+ObzTvN0UtWOWObfBVQ0JuNTpQ3n9ZLMZqX11XfFCtBj+AsoNRVr3hAlqhf
mk/bOFhidttZFY8KemfiRge8smv8REGvEH7H0p+ZrjjXwbH+Swkb991Y/HxDjqLU
6oKefeI76NuCjRTYQ4cwfaPylq0aMX3HwAaMfZSWT+GW3Tah+jr46MfIcmItb/3h
GPVGmV1NfNEw3Es/aNZ4GsM1RM0C89FwrAINQ7nn9ZDnVYXkr6JHYz7VbfYcn4OK
1hTPprVnifns7ox1XxhDzC56n7pZ3p9MMyEDNcbpuDgasuiRREDrPIrqA+0f/PTF
InQoJTJtCIJYR9mJL73Eb58HdlbV7GxEtpJMPnRi6cPk51dozNP4MCFSk4a4Kaqj
ZLhhzkgDStsOKxX+mS0GmA5m3dtSKIkzkAopyK0W2O7VxkpMzfaLXYL417lFnbkH
u2bs3WghcRpye6q2MeuUaAwl695LA94G/DVvT2xzLvqsIdG6mU+hZEXPA8vTay45
x0MqD5rGFfAX1V7GbkSTWPsHmm2WgM5MU3ogl8wN5Tfd3aW5gDpOMjv6eqvX6m+T
mZpdChz/BPnxZXsdAGxDuAg16LDcR6mfn8CfDRBdvhyS6p70asF31X/V0nT2tnsW
D1bpigIeelX2Tc+NA3qC2r2mgmkidg/bEkgVX2rEWk0JYgTF5ihBqDBt+FSPEluw
/rkg/FcYDaTY6OCE4dHJcYStXPJzYOi1NzImdy4C9KzGLE4IkkwV8bdcl+7a1aGn
v7btISEw5sUfRbpbKn23NYjx0MSNDntjV8FLoFRw/sWYESc3zxfNaltm9EnU0NDS
XUfAYqJ0KObD9S4vJzOfDBxLrIlwPu3tHhoHqD9+YWsj4Xs/EcCsOcVq3ebzzrXw
qw4chMAwlW5872m3C1W4+oobJ/bxe5LPVFTgYNfezd4JFM1f2LS0DvRGuiXBdmQo
42c1TVCmCcGSPAagxzjsrCQLRR+IDB556GhelqV/S0qUuL4i7V1fL85np3wkhLf4
dNL1PXmb/CyWwMfSxzYia0gZVFVhXxhnUw7GW2Q7eUgen5jADLgQtbKpYhQXXoHM
MZWmMnEcKH1STBzacfijC+ZeGEk1YBolwtCvjcvEs6SrJAEGSkgPQOdSWxU1ERCs
5PLLtyock0ljxzSnE8KqDP6uyxSb7OUVJA0Hd0ZZO9tdJsbQHxUz4xqvQyyOTWXO
9tBqkLdb7Y8RV4K/GI741CLd1Xzk3x5Bc3lcubpFDujhT7RuPdvexQK8ebgh+H24
IuZpxaVYR75Ole+Leo2hy4IHbOFRdrjKFsORXF1RW5YFaR/pr0SogiyV7E2D3HEL
IxGuWxX/kc4P/mJ85r2hcIZqubNaXTvjfudxCfWBjO8PgV4HjyCcVDd3W9F+Y+ls
Ob0OwmrWo7+O7L+W70nGfPKYDSnVO3EQ6S6e2aJ5v+ppunkv/5luBnk6wHYQAGrR
/YYIoJY7gug5Mi2vDy6iy2vBugvh6htTjzt3NgSCom7neEeuytfNj3pcDOoHB5iZ
5gMABrHZBUsPNe6bmjFicfrAQ31KAUsX/F2R7cJgHYL8BTbe4MGcFx/bFb8X3ttX
t5RfrLlqZp2/oftmhpVEbkVFUhmV6UWTxWwRYadTBSqb3m8ViGwDYCu9kNx/aJY7
jmXxkjeWz74/lgwy/bDcYVtqHLrVriGAchckw+NKgJtr0VHN/XPF8aAP7nTki2Ox
/LYMs7aupUpzYdAORe5IqJ30MFxvJVUaZZAygsQT9GFawEknxTBFBmLq9/ElYknP
pi/76xvoR1wW2tlcV4AQ17B2i7Zc1HvjsbKrg1o7bqeOYE2U9AGmZh7TwWOg5yOe
PZV6EQxWI9HZpUAPIt9kTnchWvxN4+vmcyk2GqJshjPat/+zksIrUZzSpfXU6tyk
pNLFoSh8WkjafGJYt+SVa/OmmyB8riWIkxGyuP1pDhZb5aWzuCIQ7GImca2PEGa4
CTiTlZJsy7LAaupDDOWHykqXmxFLsj3IjCn+sSfFlW10oqz4mN/qwPN58rCyhEQA
GckW/GoiFy0kE1jLEwz9Mw==
//pragma protect end_data_block
//pragma protect digest_block
XZWutD6x3v+QG8/ZWCqsPnOKeZ0=
//pragma protect end_digest_block
//pragma protect end_protected
